// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DataLayer.Context
{
    using DataLayer.Entities;
    using DataLayer.Maps;
    using DataLayer.Repositories;

    public partial class DataLayerDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<DataLayerDbContext>
    {
        public DataLayerDbContext Create()
        {
            return new DataLayerDbContext();
        }
    }
}
// </auto-generated>
